# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -ldflags "-X main.Version=${{  github.ref_name }}" "-X main.Brancd=master" main.go

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "mock-exporter"
        token: ${{ secrets.MY_TOKEN }}
        allowUpdates: true
        
